        	scrollModel: {autoFit: true},  
            selectionModel: {type: 'row', mode: 'single', toggle: false},
        	numberCell: { show: false },
        	title: "Listing",
        	virtualX: true, 
            virtualY: true,
            resizable: true,
            columnTemplate: {render: commentRender},

            height: 'flex',
            width: '100%',
            //flex: {one: true},
            //pageModel: { type: "local", rPP: 50, rPPOptions: [10, 50, 100, 500, 1000] },            
            showBottom: true,
            showTop: true,
            showHeader: true,
            wrap: false, 
            hwrap: false,
            editable: false,   
            bubble: false,
            toolPanel: {show:false},
            collapsible: false,
            stripRows: true,
            roundCorners: false,
            columnBorders: false,
            rowBorders: true,
            