
on:
  push:
    branches:
      - githubactions
    paths: 
      - 'Project/**'
  pull_request:
    branches:
      - githubactions
    paths: 
      - 'Project/**'
  workflow_dispatch:

jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Action Mac
        run: |
         ./scripts/compile.sh
      - uses: actions/upload-artifact@v3
        with:
         name: 'Uploading artifacts'
         path: /Users/runner/Library/Logs/DiagnosticReports/           
