//%attributes = {"shared":true}
// ----------------------------------------------------
// Project Method: iLB_Hook_ObjectMethod

//  ` This hook is called before the default Object Method for the listbox in the pointer object.
// Here you can override the default actions for the following events:

//    On Clicked 
//    On Header Clicked 
//    On After Sort 
//    On Selection Changed 
//    On Double Clicked 
//    On Drag Over 
//    On Drop 
//    On Begin Drag Over 
//    On Mouse Enter 
//    On Mouse Move 
//    On Mouse Leave 

// Access: Shared

// Parameters: $1=Table No = Longint; $2 = View No = Longint

// Returns: 1 or 0 -- pass 0 if you are handling the action, 1 if you want to use the default action


// Go to the example database to copy the example for this method
// This method was automatically generated by iLB on Mar 23, 2012.
// iLB is Copyright 2009 - 2012-- IBB Consulting, LLC 
// ----------------------------------------------------

C_POINTER:C301($1; $ptrObject)
C_LONGINT:C283($2; $iTable)
C_LONGINT:C283($3; $iView)
C_LONGINT:C283($0)

$ptrObject:=$1
$iTable:=$2
$iView:=$3
C_TEXT:C284($tCXRSet; $varName)
C_POINTER:C301($ptrMainListBox)
C_LONGINT:C283($vi_WindowRef; $iTableNum; $iFieldNum)

$tCXRSet:="$"+Table name:C256($iTable)+"_LBSet"
If (Records in set:C195($tCXRSet)=0)
	CREATE EMPTY SET:C140(Table:C252($iTable)->; $tCXRSet)
End if 

$ptrMainListBox:=OBJECT Get pointer:C1124(Object named:K67:5; "mainListBox")
If (Records in set:C195(iLB_Get_SetName($ptrMainListBox))>0)  //3/9/19 IBB changed to get pointer
	COPY SET:C600(iLB_Get_SetName($ptrMainListBox); $tCXRSet)
End if 

Case of 
	: ($iTable=Table:C252(->[Sync_Queue:30])) & (Form event code:C388=On Double Clicked:K2:5)
		$vi_WindowRef:=Open form window:C675([CompanyInfo:7]; "SyncRecord"; Plain window:K34:13; Horizontally centered:K39:1; Vertically centered:K39:4)
		SET WINDOW TITLE:C213("Sync Record - "+[Sync_Queue:30]PK:1; $vi_WindowRef)
		DIALOG:C40([CompanyInfo:7]; "SyncRecord")
		CLOSE WINDOW:C154
		$0:=0
		
	: (Form event code:C388=On Double Clicked:K2:5)
		RESOLVE POINTER:C394($ptrObject; $varName; $iTableNum; $iFieldNum)
		If ($varName="mainListbox")
			handledoubleclickevent
		End if 
		$0:=0  //don't try and open a windo
		
	Else 
		
		$0:=1  //pass on thru
End case 


//COPY SET(iLB_Get_SetName ($ptrObject);"$"+Table name($iTable)+"_LBSet")


