//%attributes = {}
declareSummaryVars


vSumOpeningCredits:=vSumTotalCredits-vSumCredits
vSumOpeningDebits:=vSumTotalDebits-vSumDebits
vSumOpeningBalance:=vSumOpeningDebits-vSumOpeningCredits

vSumOpeningCreditsLocal:=vSumTotalCreditsLocal-vSumCreditsLocal
vSumOpeningDebitsLocal:=vSumTotalDebitsLocal-vSumDebitsLocal
vSumOpeningBalanceLocal:=vSumOpeningDebitsLocal-vSumOpeningCreditsLocal

vSumOpeningFees:=vSumTotalFees-vSumFees

vOpeningTax1Received:=vSumTax1Received-vPeriodTax1Received
vOpeningTax1Paid:=vSumTax1Paid-vPeriodTax1Paid
vOpeningTax1Balance:=vSumTax1Balance-vPeriodTax1Balance

vOpeningtax2Received:=vSumtax2Received-vPeriodtax2Received
vOpeningtax2Paid:=vSumtax2Paid-vPeriodtax2Paid
vOpeningtax2Balance:=vSumtax2Balance-vPeriodtax2Balance

vOpeningTaxesReceived:=vOpeningTax1Received+vOpeningTax2Received
vOpeningTaxesPaid:=vOpeningTax1Paid+vOpeningTax2Paid
vOpeningTaxesBalance:=vOpeningTaxesReceived-vOpeningTaxesPaid

vPeriodTaxesReceived:=vPeriodTax1Received+vPeriodTax2Received
vPeriodTaxesPaid:=vPeriodTax1Paid+vPeriodTax2Paid
vPeriodTaxesBalance:=vPeriodTaxesReceived-vPeriodTaxesPaid

vOpeningTaxesReceived:=vOpeningTax1Received+vOpeningTax2Received
vOpeningTaxesPaid:=vOpeningTax1Paid+vOpeningTax2Paid
vOpeningTaxesBalance:=vOpeningTaxesReceived-vOpeningTaxesPaid

vSumTaxesReceived:=vSumTax1Received+vSumTax2Received
vSumTaxesPaid:=vSumTax1Paid+vSumTax2Paid
vSumTaxesBalance:=vSumTaxesReceived-vSumTaxesPaid

vSumDebits:=vSumDebits-vSumTransferIns  // deduct the transfers In from the Bought trades
vSumCredits:=vSumCredits-vSumTransferOuts  // deduct the transfer out from the Sold trades

vSumTransfers:=vSumTransferIns-vSumTransferOuts  // total transfers
vMarketValue:=vMarketRate*vSumTotalBalance  // position
