//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_WAPI_hostSendBlob

// Compiler method for the WAPI_hostSendBlob method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by WAPI on Jan 13, 2019.
// ----------------------------------------------------

C_POINTER:C301(WAPI_hostSendBlob; $1)
