//%attributes = {}
// ----------------------------------------------------
// Project Method: Compiler_WAPI_hookfilterRecords

// Compiler method for the WAPI_hookFilterRecords method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by WAPI on Apr 14, 2018.
// ----------------------------------------------------

C_POINTER:C301(WAPI_hookFilterRecords; $1)
