//%attributes = {}
C_POINTER:C301($arrayKeysPtr; $arrayValuesPtr; $1; $2)
$arrayKeysPtr:=$1
$arrayValuesPtr:=$2

appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11111"; "Soybean Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11112"; "Oilseed (except Soybean) Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11113"; "Dry Pea and Bean Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11114"; "Wheat Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11115"; "Corn Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11116"; "Rice Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11119"; "Other Grain Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11121"; "Vegetable and Melon Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11131"; "Orange Groves")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11132"; "Citrus (except Orange) Groves")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11133"; "Noncitrus Fruit and Tree Nut Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11141"; "Food Crops Grown Under Cover")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11142"; "Nursery and Floriculture Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11191"; "Tobacco Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11192"; "Cotton Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11193"; "Sugarcane Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11194"; "Hay Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11199"; "All Other Crop Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11211"; "Beef Cattle Ranching and Farming, including Feedlots")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11212"; "Dairy Cattle and Milk Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11213"; "Dual-Purpose Cattle Ranching and Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11221"; "Hog and Pig Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11231"; "Chicken Egg Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11232"; "Broilers and Other Meat Type Chicken Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11233"; "Turkey Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11234"; "Poultry Hatcheries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11239"; "Other Poultry Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11241"; "Sheep Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11242"; "Goat Farming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11251"; "Aquaculture")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11291"; "Apiculture")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11292"; "Horses and Other Equine Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11293"; "Fur-Bearing Animal and Rabbit Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11299"; "All Other Animal Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11311"; "Timber Tract Operations")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11321"; "Forest Nurseries and Gathering of Forest Products")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11331"; "Logging")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11411"; "Fishing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11421"; "Hunting and Trapping")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11511"; "Support Activities for Crop Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11521"; "Support Activities for Animal Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "11531"; "Support Activities for Forestry")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21112"; "Crude Petroleum Extraction ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21113"; "Natural Gas Extraction ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21211"; "Coal Mining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21221"; "Iron Ore Mining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21222"; "Gold Ore and Silver Ore Mining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21223"; "Copper, Nickel, Lead, and Zinc Mining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21229"; "Other Metal Ore Mining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21231"; "Stone Mining and Quarrying")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21232"; "Sand, Gravel, Clay, and Ceramic and Refractory Minerals Mining and Quarrying")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21239"; "Other Nonmetallic Mineral Mining and Quarrying")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "21311"; "Support Activities for Mining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "22111"; "Electric Power Generation ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "22112"; "Electric Power Transmission, Control, and Distribution ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "22121"; "Natural Gas Distribution ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "22131"; "Water Supply and Irrigation Systems ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "22132"; "Sewage Treatment Facilities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "22133"; "Steam and Air-Conditioning Supply ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23611"; "Residential Building Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23621"; "Industrial Building Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23622"; "Commercial and Institutional Building Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23711"; "Water and Sewer Line and Related Structures Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23712"; "Oil and Gas Pipeline and Related Structures Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23713"; "Power and Communication Line and Related Structures Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23721"; "Land Subdivision")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23731"; "Highway, Street, and Bridge Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23799"; "Other Heavy and Civil Engineering Construction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23811"; "Poured Concrete Foundation and Structure Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23812"; "Structural Steel and Precast Concrete Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23813"; "Framing Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23814"; "Masonry Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23815"; "Glass and Glazing Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23816"; "Roofing Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23817"; "Siding Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23819"; "Other Foundation, Structure, and Building Exterior Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23821"; "Electrical Contractors and Other Wiring Installation Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23822"; "Plumbing, Heating, and Air-Conditioning Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23829"; "Other Building Equipment Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23831"; "Drywall and Insulation Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23832"; "Painting and Wall Covering Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23833"; "Flooring Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23834"; "Tile and Terrazzo Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23835"; "Finish Carpentry Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23839"; "Other Building Finishing Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23891"; "Site Preparation Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "23899"; "All Other Specialty Trade Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31-33"; "Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31111"; "Animal Food Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31121"; "Flour Milling and Malt Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31122"; "Starch and Vegetable Fats and Oils Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31123"; "Breakfast Cereal Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31131"; "Sugar Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31134"; "Nonchocolate Confectionery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31135"; "Chocolate and Confectionery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31141"; "Frozen Food Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31142"; "Fruit and Vegetable Canning, Pickling, and Drying")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31151"; "Dairy Product (except Frozen) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31152"; "Ice Cream and Frozen Dessert Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31161"; "Animal Slaughtering and Processing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31171"; "Seafood Product Preparation and Packaging")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31181"; "Bread and Bakery Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31182"; "Cookie, Cracker, and Pasta Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31183"; "Tortilla Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31191"; "Snack Food Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31192"; "Coffee and Tea Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31193"; "Flavoring Syrup and Concentrate Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31194"; "Seasoning and Dressing Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31199"; "All Other Food Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31211"; "Soft Drink and Ice Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31212"; "Breweries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31213"; "Wineries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31214"; "Distilleries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31223"; "Tobacco Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31311"; "Fiber, Yarn, and Thread Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31321"; "Broadwoven Fabric Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31322"; "Narrow Fabric Mills and Schiffli Machine Embroidery")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31323"; "Nonwoven Fabric Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31324"; "Knit Fabric Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31331"; "Textile and Fabric Finishing Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31332"; "Fabric Coating Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31411"; "Carpet and Rug Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31412"; "Curtain and Linen Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31491"; "Textile Bag and Canvas Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31499"; "All Other Textile Product Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31511"; "Hosiery and Sock Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31519"; "Other Apparel Knitting Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31521"; "Cut and Sew Apparel Contractors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31522"; "Men’s and Boys’ Cut and Sew Apparel Manufacturing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31524"; "Women’s, Girls’, and Infants’ Cut and Sew Apparel Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31528"; "Other Cut and Sew Apparel Manufacturing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31599"; "Apparel Accessories and Other Apparel Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31611"; "Leather and Hide Tanning and Finishing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31621"; "Footwear Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "31699"; "Other Leather and Allied Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32111"; "Sawmills and Wood Preservation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32121"; "Veneer, Plywood, and Engineered Wood Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32191"; "Millwork")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32192"; "Wood Container and Pallet Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32199"; "All Other Wood Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32211"; "Pulp Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32212"; "Paper Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32213"; "Paperboard Mills")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32221"; "Paperboard Container Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32222"; "Paper Bag and Coated and Treated Paper Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32223"; "Stationery Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32229"; "Other Converted Paper Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32311"; "Printing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32312"; "Support Activities for Printing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32411"; "Petroleum Refineries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32412"; "Asphalt Paving, Roofing, and Saturated Materials Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32419"; "Other Petroleum and Coal Products Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32511"; "Petrochemical Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32512"; "Industrial Gas Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32513"; "Synthetic Dye and Pigment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32518"; "Other Basic Inorganic Chemical Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32519"; "Other Basic Organic Chemical Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32521"; "Resin and Synthetic Rubber Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32522"; "Artificial and Synthetic Fibers and Filaments Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32531"; "Fertilizer Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32532"; "Pesticide and Other Agricultural Chemical Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32541"; "Pharmaceutical and Medicine Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32551"; "Paint and Coating Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32552"; "Adhesive Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32561"; "Soap and Cleaning Compound Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32562"; "Toilet Preparation Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32591"; "Printing Ink Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32592"; "Explosives Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32599"; "All Other Chemical Product and Preparation Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32611"; "Plastics Packaging Materials and Unlaminated Film and Sheet Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32612"; "Plastics Pipe, Pipe Fitting, and Unlaminated Profile Shape Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32613"; "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32614"; "Polystyrene Foam Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32615"; "Urethane and Other Foam Product (except Polystyrene) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32616"; "Plastics Bottle Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32619"; "Other Plastics Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32621"; "Tire Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32622"; "Rubber and Plastics Hoses and Belting Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32629"; "Other Rubber Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32711"; "Pottery, Ceramics, and Plumbing Fixture Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32712"; "Clay Building Material and Refractories Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32721"; "Glass and Glass Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32731"; "Cement Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32732"; "Ready-Mix Concrete Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32733"; "Concrete Pipe, Brick, and Block Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32739"; "Other Concrete Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32741"; "Lime Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32742"; "Gypsum Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32791"; "Abrasive Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "32799"; "All Other Nonmetallic Mineral Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33111"; "Iron and Steel Mills and Ferroalloy Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33121"; "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33122"; "Rolling and Drawing of Purchased Steel")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33131"; "Alumina and Aluminum Production and Processing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33141"; "Nonferrous Metal (except Aluminum) Smelting and Refining")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33142"; "Copper Rolling, Drawing, Extruding, and Alloying")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33149"; "Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, Extruding, and Alloying")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33151"; "Ferrous Metal Foundries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33152"; "Nonferrous Metal Foundries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33211"; "Forging and Stamping")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33221"; "Cutlery and Handtool Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33231"; "Plate Work and Fabricated Structural Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33232"; "Ornamental and Architectural Metal Products Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33241"; "Power Boiler and Heat Exchanger Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33242"; "Metal Tank (Heavy Gauge) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33243"; "Metal Can, Box, and Other Metal Container (Light Gauge) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33251"; "Hardware Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33261"; "Spring and Wire Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33271"; "Machine Shops")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33272"; "Turned Product and Screw, Nut, and Bolt Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33281"; "Coating, Engraving, Heat Treating, and Allied Activities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33291"; "Metal Valve Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33299"; "All Other Fabricated Metal Product Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33311"; "Agricultural Implement Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33312"; "Construction Machinery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33313"; "Mining and Oil and Gas Field Machinery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33324"; "Industrial Machinery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33331"; "Commercial and Service Industry Machinery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33341"; "Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33351"; "Metalworking Machinery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33361"; "Engine, Turbine, and Power Transmission Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33391"; "Pump and Compressor Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33392"; "Material Handling Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33399"; "All Other General Purpose Machinery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33411"; "Computer and Peripheral Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33421"; "Telephone Apparatus Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33422"; "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33429"; "Other Communications Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33431"; "Audio and Video Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33441"; "Semiconductor and Other Electronic Component Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33451"; "Navigational, Measuring, Electromedical, and Control Instruments Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33461"; "Manufacturing and Reproducing Magnetic and Optical Media")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33511"; "Electric Lamp Bulb and Part Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33512"; "Lighting Fixture Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33521"; "Small Electrical Appliance Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33522"; "Major Household Appliance Manufacturing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33531"; "Electrical Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33591"; "Battery Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33592"; "Communication and Energy Wire and Cable Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33593"; "Wiring Device Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33599"; "All Other Electrical Equipment and Component Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33611"; "Automobile and Light Duty Motor Vehicle Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33612"; "Heavy Duty Truck Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33621"; "Motor Vehicle Body and Trailer Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33631"; "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33632"; "Motor Vehicle Electrical and Electronic Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33633"; "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33634"; "Motor Vehicle Brake System Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33635"; "Motor Vehicle Transmission and Power Train Parts Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33636"; "Motor Vehicle Seating and Interior Trim Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33637"; "Motor Vehicle Metal Stamping")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33639"; "Other Motor Vehicle Parts Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33641"; "Aerospace Product and Parts Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33651"; "Railroad Rolling Stock Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33661"; "Ship and Boat Building")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33699"; "Other Transportation Equipment Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33711"; "Wood Kitchen Cabinet and Countertop Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33712"; "Household and Institutional Furniture Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33721"; "Office Furniture (including Fixtures) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33791"; "Mattress Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33792"; "Blind and Shade Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33911"; "Medical Equipment and Supplies Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33991"; "Jewelry and Silverware Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33992"; "Sporting and Athletic Goods Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33993"; "Doll, Toy, and Game Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33994"; "Office Supplies (except Paper) Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33995"; "Sign Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "33999"; "All Other Miscellaneous Manufacturing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42311"; "Automobile and Other Motor Vehicle Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42312"; "Motor Vehicle Supplies and New Parts Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42313"; "Tire and Tube Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42314"; "Motor Vehicle Parts (Used) Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42321"; "Furniture Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42322"; "Home Furnishing Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42331"; "Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42332"; "Brick, Stone, and Related Construction Material Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42333"; "Roofing, Siding, and Insulation Material Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42339"; "Other Construction Material Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42341"; "Photographic Equipment and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42342"; "Office Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42343"; "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42344"; "Other Commercial Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42345"; "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42346"; "Ophthalmic Goods Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42349"; "Other Professional Equipment and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42351"; "Metal Service Centers and Other Metal Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42352"; "Coal and Other Mineral and Ore Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42361"; "Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42362"; "Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42369"; "Other Electronic Parts and Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42371"; "Hardware Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42372"; "Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42373"; "Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42374"; "Refrigeration Equipment and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42381"; "Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42382"; "Farm and Garden Machinery and Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42383"; "Industrial Machinery and Equipment Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42384"; "Industrial Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42385"; "Service Establishment Equipment and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42386"; "Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42391"; "Sporting and Recreational Goods and Supplies Merchant Wholesalers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42392"; "Toy and Hobby Goods and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42393"; "Recyclable Material Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42394"; "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42399"; "Other Miscellaneous Durable Goods Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42411"; "Printing and Writing Paper Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42412"; "Stationery and Office Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42413"; "Industrial and Personal Service Paper Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42421"; "Drugs and Druggists' Sundries Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42431"; "Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42432"; "Men's and Boys' Clothing and Furnishings Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42433"; "Women's, Children's, and Infants' Clothing and Accessories Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42434"; "Footwear Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42441"; "General Line Grocery Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42442"; "Packaged Frozen Food Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42443"; "Dairy Product (except Dried or Canned) Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42444"; "Poultry and Poultry Product Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42445"; "Confectionery Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42446"; "Fish and Seafood Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42447"; "Meat and Meat Product Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42448"; "Fresh Fruit and Vegetable Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42449"; "Other Grocery and Related Products Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42451"; "Grain and Field Bean Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42452"; "Livestock Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42459"; "Other Farm Product Raw Material Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42461"; "Plastics Materials and Basic Forms and Shapes Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42469"; "Other Chemical and Allied Products Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42471"; "Petroleum Bulk Stations and Terminals ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42472"; "Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals) ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42481"; "Beer and Ale Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42482"; "Wine and Distilled Alcoholic Beverage Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42491"; "Farm Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42492"; "Book, Periodical, and Newspaper Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42493"; "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42494"; "Tobacco and Tobacco Product Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42495"; "Paint, Varnish, and Supplies Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42499"; "Other Miscellaneous Nondurable Goods Merchant Wholesalers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42511"; "Business to Business Electronic Markets ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "42512"; "Wholesale Trade Agents and Brokers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44-45"; "Retail Trade")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44111"; "New Car Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44112"; "Used Car Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44121"; "Recreational Vehicle Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44122"; "Motorcycle, Boat, and Other Motor Vehicle Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44131"; "Automotive Parts and Accessories Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44132"; "Tire Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44211"; "Furniture Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44221"; "Floor Covering Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44229"; "Other Home Furnishings Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44314"; "Electronics and Appliance Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44411"; "Home Centers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44412"; "Paint and Wallpaper Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44413"; "Hardware Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44419"; "Other Building Material Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44421"; "Outdoor Power Equipment Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44422"; "Nursery, Garden Center, and Farm Supply Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44511"; "Supermarkets and Other Grocery (except Convenience) Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44512"; "Convenience Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44521"; "Meat Markets ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44522"; "Fish and Seafood Markets ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44523"; "Fruit and Vegetable Markets ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44529"; "Other Specialty Food Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44531"; "Beer, Wine, and Liquor Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44611"; "Pharmacies and Drug Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44612"; "Cosmetics, Beauty Supplies, and Perfume Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44613"; "Optical Goods Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44619"; "Other Health and Personal Care Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44711"; "Gasoline Stations with Convenience Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44719"; "Other Gasoline Stations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44811"; "Men's Clothing Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44812"; "Women's Clothing Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44813"; "Children's and Infants' Clothing Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44814"; "Family Clothing Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44815"; "Clothing Accessories Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44819"; "Other Clothing Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44821"; "Shoe Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44831"; "Jewelry Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "44832"; "Luggage and Leather Goods Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45111"; "Sporting Goods Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45112"; "Hobby, Toy, and Game Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45113"; "Sewing, Needlework, and Piece Goods Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45114"; "Musical Instrument and Supplies Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45121"; "Book Stores and News Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45221"; "Department Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45231"; "General Merchandise Stores, including Warehouse Clubs and Supercenters ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45311"; "Florists ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45321"; "Office Supplies and Stationery Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45322"; "Gift, Novelty, and Souvenir Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45331"; "Used Merchandise Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45391"; "Pet and Pet Supplies Stores ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45392"; "Art Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45393"; "Manufactured (Mobile) Home Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45399"; "All Other Miscellaneous Store Retailers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45411"; "Electronic Shopping and Mail-Order Houses ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45421"; "Vending Machine Operators ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45431"; "Fuel Dealers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "45439"; "Other Direct Selling Establishments ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48-49"; "Transportation and Warehousing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48111"; "Scheduled Air Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48121"; "Nonscheduled Air Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48211"; "Rail Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48311"; "Deep Sea, Coastal, and Great Lakes Water Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48321"; "Inland Water Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48411"; "General Freight Trucking, Local")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48412"; "General Freight Trucking, Long-Distance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48421"; "Used Household and Office Goods Moving")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48422"; "Specialized Freight (except Used Goods) Trucking, Local")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48423"; "Specialized Freight (except Used Goods) Trucking, Long-Distance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48511"; "Urban Transit Systems")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48521"; "Interurban and Rural Bus Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48531"; "Taxi Service")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48532"; "Limousine Service")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48541"; "School and Employee Bus Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48551"; "Charter Bus Industry")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48599"; "Other Transit and Ground Passenger Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48611"; "Pipeline Transportation of Crude Oil")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48621"; "Pipeline Transportation of Natural Gas")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48691"; "Pipeline Transportation of Refined Petroleum Products")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48699"; "All Other Pipeline Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48711"; "Scenic and Sightseeing Transportation, Land")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48721"; "Scenic and Sightseeing Transportation, Water")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48799"; "Scenic and Sightseeing Transportation, Other")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48811"; "Airport Operations")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48819"; "Other Support Activities for Air Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48821"; "Support Activities for Rail Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48831"; "Port and Harbor Operations")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48832"; "Marine Cargo Handling")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48833"; "Navigational Services to Shipping")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48839"; "Other Support Activities for Water Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48841"; "Motor Vehicle Towing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48849"; "Other Support Activities for Road Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48851"; "Freight Transportation Arrangement")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "48899"; "Other Support Activities for Transportation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49111"; "Postal Service")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49211"; "Couriers and Express Delivery Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49221"; "Local Messengers and Local Delivery")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49311"; "General Warehousing and Storage")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49312"; "Refrigerated Warehousing and Storage")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49313"; "Farm Product Warehousing and Storage")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "49319"; "Other Warehousing and Storage")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51111"; "Newspaper Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51112"; "Periodical Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51113"; "Book Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51114"; "Directory and Mailing List Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51119"; "Other Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51121"; "Software Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51211"; "Motion Picture and Video Production")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51212"; "Motion Picture and Video Distribution")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51213"; "Motion Picture and Video Exhibition")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51219"; "Postproduction Services and Other Motion Picture and Video Industries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51223"; "Music Publishers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51224"; "Sound Recording Studios")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51225"; "Record Production and Distribution")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51229"; "Other Sound Recording Industries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51511"; "Radio Broadcasting")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51512"; "Television Broadcasting")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51521"; "Cable and Other Subscription Programming")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51731"; "Wired and Wireless Telecommunications Carriers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51741"; "Satellite Telecommunications")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51791"; "Other Telecommunications")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51821"; "Data Processing, Hosting, and Related Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51911"; "News Syndicates")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51912"; "Libraries and Archives")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51913"; "Internet Publishing and Broadcasting and Web Search Portals")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "51919"; "All Other Information Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52111"; "Monetary Authorities-Central Bank")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52211"; "Commercial Banking ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52212"; "Savings Institutions ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52213"; "Credit Unions ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52219"; "Other Depository Credit Intermediation ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52221"; "Credit Card Issuing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52222"; "Sales Financing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52229"; "Other Nondepository Credit Intermediation ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52231"; "Mortgage and Nonmortgage Loan Brokers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52232"; "Financial Transactions Processing, Reserve, and Clearinghouse Activities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52239"; "Other Activities Related to Credit Intermediation ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52311"; "Investment Banking and Securities Dealing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52312"; "Securities Brokerage ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52313"; "Commodity Contracts Dealing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52314"; "Commodity Contracts Brokerage ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52321"; "Securities and Commodity Exchanges")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52391"; "Miscellaneous Intermediation ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52392"; "Portfolio Management ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52393"; "Investment Advice ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52399"; "All Other Financial Investment Activities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52411"; "Direct Life, Health, and Medical Insurance Carriers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52412"; "Direct Insurance (except Life, Health, and Medical) Carriers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52413"; "Reinsurance Carriers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52421"; "Insurance Agencies and Brokerages ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52429"; "Other Insurance Related Activities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52511"; "Pension Funds ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52512"; "Health and Welfare Funds ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52519"; "Other Insurance Funds ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52591"; "Open-End Investment Funds ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52592"; "Trusts, Estates, and Agency Accounts ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "52599"; "Other Financial Vehicles ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53111"; "Lessors of Residential Buildings and Dwellings ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53112"; "Lessors of Nonresidential Buildings (except Miniwarehouses) ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53113"; "Lessors of Miniwarehouses and Self-Storage Units ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53119"; "Lessors of Other Real Estate Property ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53121"; "Offices of Real Estate Agents and Brokers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53131"; "Real Estate Property Managers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53132"; "Offices of Real Estate Appraisers ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53139"; "Other Activities Related to Real Estate ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53211"; "Passenger Car Rental and Leasing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53212"; "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53221"; "Consumer Electronics and Appliances Rental")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53228"; "Other Consumer Goods Rental ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53231"; "General Rental Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53241"; "Construction, Transportation, Mining, and Forestry Machinery and Equipment Rental and Leasing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53242"; "Office Machinery and Equipment Rental and Leasing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53249"; "Other Commercial and Industrial Machinery and Equipment Rental and Leasing")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "53311"; "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54111"; "Offices of Lawyers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54112"; "Offices of Notaries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54119"; "Other Legal Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54121"; "Accounting, Tax Preparation, Bookkeeping, and Payroll Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54131"; "Architectural Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54132"; "Landscape Architectural Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54133"; "Engineering Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54134"; "Drafting Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54135"; "Building Inspection Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54136"; "Geophysical Surveying and Mapping Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54137"; "Surveying and Mapping (except Geophysical) Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54138"; "Testing Laboratories")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54141"; "Interior Design Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54142"; "Industrial Design Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54143"; "Graphic Design Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54149"; "Other Specialized Design Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54151"; "Computer Systems Design and Related Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54161"; "Management Consulting Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54162"; "Environmental Consulting Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54169"; "Other Scientific and Technical Consulting Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54171"; "Research and Development in the Physical, Engineering, and Life Sciences")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54172"; "Research and Development in the Social Sciences and Humanities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54181"; "Advertising Agencies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54182"; "Public Relations Agencies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54183"; "Media Buying Agencies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54184"; "Media Representatives")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54185"; "Outdoor Advertising")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54186"; "Direct Mail Advertising")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54187"; "Advertising Material Distribution Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54189"; "Other Services Related to Advertising")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54191"; "Marketing Research and Public Opinion Polling")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54192"; "Photographic Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54193"; "Translation and Interpretation Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54194"; "Veterinary Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "54199"; "All Other Professional, Scientific, and Technical Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "55111"; "Management of Companies and Enterprises")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56111"; "Office Administrative Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56121"; "Facilities Support Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56131"; "Employment Placement Agencies and Executive Search Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56132"; "Temporary Help Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56133"; "Professional Employer Organizations")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56141"; "Document Preparation Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56142"; "Telephone Call Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56143"; "Business Service Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56144"; "Collection Agencies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56145"; "Credit Bureaus")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56149"; "Other Business Support Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56151"; "Travel Agencies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56152"; "Tour Operators")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56159"; "Other Travel Arrangement and Reservation Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56161"; "Investigation, Guard, and Armored Car Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56162"; "Security Systems Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56171"; "Exterminating and Pest Control Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56172"; "Janitorial Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56173"; "Landscaping Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56174"; "Carpet and Upholstery Cleaning Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56179"; "Other Services to Buildings and Dwellings")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56191"; "Packaging and Labeling Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56192"; "Convention and Trade Show Organizers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56199"; "All Other Support Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56211"; "Waste Collection ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56221"; "Waste Treatment and Disposal ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56291"; "Remediation Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56292"; "Materials Recovery Facilities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "56299"; "All Other Waste Management Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61111"; "Elementary and Secondary Schools ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61121"; "Junior Colleges")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61131"; "Colleges, Universities, and Professional Schools")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61141"; "Business and Secretarial Schools")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61142"; "Computer Training")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61143"; "Professional and Management Development Training")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61151"; "Technical and Trade Schools")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61161"; "Fine Arts Schools")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61162"; "Sports and Recreation Instruction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61163"; "Language Schools")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61169"; "All Other Schools and Instruction")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "61171"; "Educational Support Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62111"; "Offices of Physicians")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62121"; "Offices of Dentists")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62131"; "Offices of Chiropractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62132"; "Offices of Optometrists")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62133"; "Offices of Mental Health Practitioners (except Physicians)")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62134"; "Offices of Physical, Occupational and Speech Therapists, and Audiologists")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62139"; "Offices of All Other Health Practitioners")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62141"; "Family Planning Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62142"; "Outpatient Mental Health and Substance Abuse Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62149"; "Other Outpatient Care Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62151"; "Medical and Diagnostic Laboratories")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62161"; "Home Health Care Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62191"; "Ambulance Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62199"; "All Other Ambulatory Health Care Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62211"; "General Medical and Surgical Hospitals")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62221"; "Psychiatric and Substance Abuse Hospitals")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62231"; "Specialty (except Psychiatric and Substance Abuse) Hospitals")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62311"; "Nursing Care Facilities (Skilled Nursing Facilities)")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62321"; "Residential Intellectual and Developmental Disability Facilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62322"; "Residential Mental Health and Substance Abuse Facilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62331"; "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62399"; "Other Residential Care Facilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62411"; "Child and Youth Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62412"; "Services for the Elderly and Persons with Disabilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62419"; "Other Individual and Family Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62421"; "Community Food Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62422"; "Community Housing Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62423"; "Emergency and Other Relief Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62431"; "Vocational Rehabilitation Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "62441"; "Child Day Care Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71111"; "Theater Companies and Dinner Theaters")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71112"; "Dance Companies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71113"; "Musical Groups and Artists")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71119"; "Other Performing Arts Companies")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71121"; "Spectator Sports")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71131"; "Promoters of Performing Arts, Sports, and Similar Events with Facilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71132"; "Promoters of Performing Arts, Sports, and Similar Events without Facilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71141"; "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71151"; "Independent Artists, Writers, and Performers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71211"; "Museums")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71212"; "Historical Sites")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71213"; "Zoos and Botanical Gardens")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71219"; "Nature Parks and Other Similar Institutions")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71311"; "Amusement and Theme Parks")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71312"; "Amusement Arcades")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71321"; "Casinos (except Casino Hotels)")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71329"; "Other Gambling Industries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71391"; "Golf Courses and Country Clubs")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71392"; "Skiing Facilities")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71393"; "Marinas")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71394"; "Fitness and Recreational Sports Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71395"; "Bowling Centers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "71399"; "All Other Amusement and Recreation Industries")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72111"; "Hotels (except Casino Hotels) and Motels")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72112"; "Casino Hotels")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72119"; "Other Traveler Accommodation")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72121"; "RV (Recreational Vehicle) Parks and Recreational Camps")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72131"; "Rooming and Boarding Houses, Dormitories, and Workers' Camps")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72231"; "Food Service Contractors")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72232"; "Caterers")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72233"; "Mobile Food Services")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72241"; "Drinking Places (Alcoholic Beverages)")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "72251"; "Restaurants and Other Eating Places")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81111"; "Automotive Mechanical and Electrical Repair and Maintenance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81112"; "Automotive Body, Paint, Interior, and Glass Repair")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81119"; "Other Automotive Repair and Maintenance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81121"; "Electronic and Precision Equipment Repair and Maintenance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81131"; "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81141"; "Home and Garden Equipment and Appliance Repair and Maintenance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81142"; "Reupholstery and Furniture Repair")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81143"; "Footwear and Leather Goods Repair")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81149"; "Other Personal and Household Goods Repair and Maintenance")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81211"; "Hair, Nail, and Skin Care Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81219"; "Other Personal Care Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81221"; "Funeral Homes and Funeral Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81222"; "Cemeteries and Crematories ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81231"; "Coin-Operated Laundries and Drycleaners ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81232"; "Drycleaning and Laundry Services (except Coin-Operated) ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81233"; "Linen and Uniform Supply ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81291"; "Pet Care (except Veterinary) Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81292"; "Photofinishing ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81293"; "Parking Lots and Garages ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81299"; "All Other Personal Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81311"; "Religious Organizations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81321"; "Grantmaking and Giving Services ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81331"; "Social Advocacy Organizations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81341"; "Civic and Social Organizations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81391"; "Business Associations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81392"; "Professional Organizations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81393"; "Labor Unions and Similar Labor Organizations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81394"; "Political Organizations ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81399"; "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations) ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "81411"; "Private Households")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92111"; "Executive Offices ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92112"; "Legislative Bodies ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92113"; "Public Finance Activities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92114"; "Executive and Legislative Offices, Combined ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92115"; "American Indian and Alaska Native Tribal Governments ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92119"; "Other General Government Support ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92211"; "Courts ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92212"; "Police Protection ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92213"; "Legal Counsel and Prosecution ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92214"; "Correctional Institutions ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92215"; "Parole Offices and Probation Offices ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92216"; "Fire Protection ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92219"; "Other Justice, Public Order, and Safety Activities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92311"; "Administration of Education Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92312"; "Administration of Public Health Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92313"; "Administration of Human Resource Programs (except Education, Public Health, and Veterans' Affairs Programs) ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92314"; "Administration of Veterans' Affairs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92411"; "Administration of Air and Water Resource and Solid Waste Management Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92412"; "Administration of Conservation Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92511"; "Administration of Housing Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92512"; "Administration of Urban Planning and Community and Rural Development ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92611"; "Administration of General Economic Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92612"; "Regulation and Administration of Transportation Programs ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92613"; "Regulation and Administration of Communications, Electric, Gas, and Other Utilities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92614"; "Regulation of Agricultural Marketing and Commodities ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92615"; "Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors ")
appendKeyValueToArrays($arrayKeysPtr; $arrayValuesPtr; "92711"; "Space Research and Technology ")
