//%attributes = {}
// ----------------------------------------------------
// Project Method: Compiler_WAPI_hostListToArray

// Compiler method for the WAPI_hostListToArray method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by WAPI on Apr 14, 2018.
// ----------------------------------------------------

C_TEXT:C284(WAPI_hostListToArray; $1)
C_POINTER:C301(WAPI_hostListToArray; $2)
