//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_WAPI_hostSendFile

// Compiler method for the WAPI_hostSendFile method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by WAPI on Jan 13, 2019.
// ----------------------------------------------------

C_TEXT:C284(WAPI_hostSendFile; $1)
