//%attributes = {}
// ----------------------------------------------------
// Project Method: Compiler_WAPI_filterRecords

// Compiler method for the WAPI_filterRecords method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by iLB on Mar 22, 2018.
// ----------------------------------------------------

C_POINTER:C301(WAPI_hookFilterRecords; $1)
