name: release on Win Server runner

on:
  push:
    branches: 
  #    - main
  workflow_dispatch:
  # schedule:
    # - cron: '30 4 * * *' #build every day at 4:30 UTC

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Action Windows
        env:
          WHO_TO_TRUST: ${{secrets.MYTOKEN}}
          RUNNER_ACTOR: ${{github.actor}}
          RUNNER: GIT
          BINARIES_USER: ${{secrets.BINARIES_USER}}
          BINARIES_PASSWORD: ${{secrets.BINARIES_PASSWORD}}
          UPLOAD_USER: ${{secrets.UPLOAD_USER}}
          UPLOAD_PASSWORD: ${{secrets.UPLOAD_PASSWORD}}
        run: |
         set jq=jq.exe
         set curl=curl.exe
         set sevenzip=7z.exe
         set workingDirectory=%GITHUB_WORKSPACE%\my4DApp
         set scripts=%workingDirectory%\buildFiles\scripts
         set params=%workingDirectory%\buildFiles\parameters.json
         echo "%params%"
         
      - uses: actions/upload-artifact@v3
        with:
         name: 'Uploading artifacts'
         path: /Users/runner/Documents/artifacts/           
